import Matrix from './components/Matrix';

function App() {
  const matrix = exampleInput2D.split('\n').map((row) => row.split(''));

  return (
    <div className="flex h-screen p-10">
      <div className="m-auto">
        <h3 className="text-5xl font-bold mb-10">Your Matrix is Below</h3>
        <Matrix matrix={matrix} />
      </div>
    </div>
  );
}

const exampleInput1D = `WWWLLLLLLLLLWWWLWWWLLLLLLWWWWW`;

const exampleInput2D = `WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWLWWWWWWWWWWWWWWWWWWWLLWWWWW
WWWWWWWWWWWWWWWWWWWWWWLLLLWWWW
WWWWWWWLWWWWWLWWWWWWWLLLLLWWWW
WLWWWLLLWWWWWWWWWWWWLLLLLLWWWW
WWWLLLLLLLLLWWWLWWWLLLLLLWWWWW
WWLLLLLLLLWWWWWWWWWLLLLLLWWWWW
WLLLLLLLLLWWWWWWWWWLLLLLLWWLWW
WLLLLLLLLWWWWWWWWWWLLLLLLWWLLW
WLLLLLLLWWWLWWWWWWWWWLLLWWWWLW
WLWWWWWWWWWWWWWWWWWWWWWWWWWWLW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWLW
WWWWWWWWWWWWWWWWWWWWLWWWWLWWWW
WWWWWWWWWLWWLWWWWWWWWWWWWWWWLW
WWWWWWWWWWWWWWLLWWWWWWWWWWWLLW
WWWWWWWWWWWWWWWWWWWWWWWWWWLLLW
WWWWWWWWLLLLWWWLWWWWWWLWWWLLLW
WWWWWWWLLLLLLWWWWWWWWWWWWWWLLW
WWWWWWWLLLLLWWWWWWWWWWWWWWWWWW
WWWWWWWWLLLWWWWWWWWWWWWWWWWWWW
WWWWWWWWLWWLWWWWWWWWWWWWWWWWWW
WLWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WLWWWWWWWWWWWWWWLLWWWWWWWWWWWW
WLWLWWWWWWWWWWWLLLLLWWWWWWWWWW
WLLWWWWWWWWWWWLLLLLLLWWWWWWWWW
WLWWWWWWWWWWWWLLLLLLLLLWWWWWWW
WLWWWWWWWWWWWLLLLLLLWWWWWWWWWW
WWWWWWWWWWWWWLLLLLLWWWWWWWWWWW
WWWWWWWWWWWWLLLLLLWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW`;

export default App;
